package com.example.model

object BoardThemes {
    val ALL_THEMES = listOf(
        BoardTheme(
            id = 1,
            name = "Classic Wood",
            unlockLevel = 1,
            description = "Handcrafted Walnut & Oak wooden board with brass inlaid points.",
            boardBackgroundColors = listOf(0xFF2C1810, 0xFF1F0E08),
            woodBorderColor = 0xFF5A3825,
            pointColorLight = 0xFFD2B48C,
            pointColorDark = 0xFF8B4513,
            checkerWhiteColors = listOf(0xFFFFF8DC, 0xFFDEB887),
            checkerBlackColors = listOf(0xFF3E2723, 0xFF1B0000),
            accentGlowColor = 0xFFFFD700,
            particleColor = 0x88FFD700,
            iconEmoji = "🪵"
        ),
        BoardTheme(
            id = 2,
            name = "Emerald Marble",
            unlockLevel = 5,
            description = "Deep jade green marble with polished gold leaf triangular points.",
            boardBackgroundColors = listOf(0xFF06302B, 0xFF021B18),
            woodBorderColor = 0xFF0D4B43,
            pointColorLight = 0xFFE0C068,
            pointColorDark = 0xFF0F5A47,
            checkerWhiteColors = listOf(0xFFF5F5DC, 0xFFC0C0C0),
            checkerBlackColors = listOf(0xFF04221D, 0xFF010E0C),
            accentGlowColor = 0xFF50C878,
            particleColor = 0x8850C878,
            iconEmoji = "❇️"
        ),
        BoardTheme(
            id = 3,
            name = "Midnight Obsidian",
            unlockLevel = 10,
            description = "Jet black volcanic glass with glowing neon violet & cyan points.",
            boardBackgroundColors = listOf(0xFF121218, 0xFF08080C),
            woodBorderColor = 0xFF2A2A38,
            pointColorLight = 0xFF00E5FF,
            pointColorDark = 0xFFBD00FF,
            checkerWhiteColors = listOf(0xFFE0F7FA, 0xFF80DEEA),
            checkerBlackColors = listOf(0xFF212121, 0xFF000000),
            accentGlowColor = 0xFF00E5FF,
            particleColor = 0x8800E5FF,
            iconEmoji = "🌌"
        ),
        BoardTheme(
            id = 4,
            name = "Royal Gold",
            unlockLevel = 15,
            description = "Solid 24K gold polished surface featuring sapphire & ruby points.",
            boardBackgroundColors = listOf(0xFF332305, 0xFF1A1202),
            woodBorderColor = 0xFFB8860B,
            pointColorLight = 0xFFDC143C,
            pointColorDark = 0xFF00008B,
            checkerWhiteColors = listOf(0xFFFFD700, 0xFFFFA500),
            checkerBlackColors = listOf(0xFF2F4F4F, 0xFF191970),
            accentGlowColor = 0xFFFFD700,
            particleColor = 0x88FFD700,
            iconEmoji = "👑"
        ),
        BoardTheme(
            id = 5,
            name = "Ocean Crystal",
            unlockLevel = 25,
            description = "Translucent deep sea sapphire crystal with pearl & coral triangular points.",
            boardBackgroundColors = listOf(0xFF082032, 0xFF030E18),
            woodBorderColor = 0xFF144272,
            pointColorLight = 0xFFF8F9FA,
            pointColorDark = 0xFFFF6B6B,
            checkerWhiteColors = listOf(0xFFE0F2FE, 0xFFBAE6FD),
            checkerBlackColors = listOf(0xFF0F172A, 0xFF020617),
            accentGlowColor = 0xFF38BDF8,
            particleColor = 0x8838BDF8,
            iconEmoji = "🌊"
        ),
        BoardTheme(
            id = 6,
            name = "Fire Ruby",
            unlockLevel = 35,
            description = "Molten crimson magma surface with burning ember points & particle sparks.",
            boardBackgroundColors = listOf(0xFF320808, 0xFF180303),
            woodBorderColor = 0xFF5C1313,
            pointColorLight = 0xFFFFA07A,
            pointColorDark = 0xFF8B0000,
            checkerWhiteColors = listOf(0xFFFFE4E1, 0xFFF08080),
            checkerBlackColors = listOf(0xFF2B0000, 0xFF140000),
            accentGlowColor = 0xFFFF4500,
            particleColor = 0x88FF4500,
            iconEmoji = "🔥"
        ),
        BoardTheme(
            id = 7,
            name = "Galactic Nebula",
            unlockLevel = 50,
            description = "Cosmic starry deep universe with shimmering galaxy cluster points.",
            boardBackgroundColors = listOf(0xFF0D0B1D, 0xFF05040B),
            woodBorderColor = 0xFF281E48,
            pointColorLight = 0xFFA78BFA,
            pointColorDark = 0xFF4C1D95,
            checkerWhiteColors = listOf(0xFFF3E8FF, 0xFFDDD6FE),
            checkerBlackColors = listOf(0xFF1E1B4B, 0xFF0F0E2A),
            accentGlowColor = 0xFFC084FC,
            particleColor = 0x88C084FC,
            iconEmoji = "✨"
        ),
        BoardTheme(
            id = 8,
            name = "Dragon Scale",
            unlockLevel = 65,
            description = "Ancient shadow dragon scales with glowing magma bloodline points.",
            boardBackgroundColors = listOf(0xFF1A1310, 0xFF0D0908),
            woodBorderColor = 0xFF3D271D,
            pointColorLight = 0xFFF97316,
            pointColorDark = 0xFF7C2D12,
            checkerWhiteColors = listOf(0xFFFED7AA, 0xFFFDBA74),
            checkerBlackColors = listOf(0xFF27150C, 0xFF140A06),
            accentGlowColor = 0xFFEA580C,
            particleColor = 0x88EA580C,
            iconEmoji = "🐉"
        ),
        BoardTheme(
            id = 9,
            name = "Celestial Diamond",
            unlockLevel = 80,
            description = "Prismatic diamond facets reflecting brilliant cosmic starlight.",
            boardBackgroundColors = listOf(0xFF182026, 0xFF0C1014),
            woodBorderColor = 0xFF30404D,
            pointColorLight = 0xFFE2E8F0,
            pointColorDark = 0xFF64748B,
            checkerWhiteColors = listOf(0xFFFFFFFF, 0xFFE2E8F0),
            checkerBlackColors = listOf(0xFF334155, 0xFF0F172A),
            accentGlowColor = 0xFF38BDF8,
            particleColor = 0x8838BDF8,
            iconEmoji = "💎"
        ),
        BoardTheme(
            id = 10,
            name = "Legendary Phoenix",
            unlockLevel = 100,
            description = "Mythical Persian sunfire phoenix wings with golden royal filigree.",
            boardBackgroundColors = listOf(0xFF2D1302, 0xFF140801),
            woodBorderColor = 0xFF7C2D12,
            pointColorLight = 0xFFFDE047,
            pointColorDark = 0xFFB45309,
            checkerWhiteColors = listOf(0xFFFEF08A, 0xFFFACC15),
            checkerBlackColors = listOf(0xFF451A03, 0xFF270E02),
            accentGlowColor = 0xFFEAB308,
            particleColor = 0x88EAB308,
            iconEmoji = "🦅"
        )
    )

    fun getThemeById(id: Int): BoardTheme = ALL_THEMES.find { it.id == id } ?: ALL_THEMES.first()
}
